APP_NAME = "patchdiff"
VERSION = "0.1.0"
DEFAULT_CONFIG_PATH = "~/.config/patchdiff/config.yaml"
DEFAULT_LOG_LEVEL = "INFO"
DEFAULT_TOP_N = 30
ENV_CONFIG_PATH = "PATCHDIFF_CONFIG"
ENV_LOG_LEVEL = "PATCHDIFF_LOG_LEVEL"
ENV_OFFLINE = "PATCHDIFF_OFFLINE"
